version: '3'
services:

  rabbitMQ:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin 
      - KEYCLOAK_ADMIN_PASSWORD=admin 
    ports:
      - 8081:8080
