version: '3'

networks:
  ms:
    name: microservices

services:

  rabbitMQ:
    image: rabbitmq:3.9-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ms

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin 
      - KEYCLOAK_ADMIN_PASSWORD=admin 
    ports:
      - 8081:8080
    networks:
      - ms