spring:
    application:
        name: mscards
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb 
        username: db
        password: 
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create

server:
    port: 0

eureka:
    client:
        register-with-eureka: true
        fetch-registry: false

    instance:
        instance-id: ${spring.application.name}:${random.value}