spring:
    application:
        name: mscards
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb 
        username: db
        password: 
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create
    rabbitmq:
        host: rabbit
        port: 5672
        username: guest
        password: guest

server:
    port: 8080

eureka:
    client:
        register-with-eureka: true
        fetch-registry: false
        service-url:
            defaultZone: http://guest:guest@mseureka:8761/eureka

    instance:
        instance-id: ${spring.application.name}:${random.value}

amqp:
    rabbit:
        queues: 
            card-issuance: card-issuance-queue

